@BASE_URL=http://localhost:5000/api
@TOKEN= Enter token generated on login 
@json=application/json


# regiser user
###
POST {{BASE_URL}}/auth/register
Content-Type: {{json}}

{
    "firstName": "User2",
    "lastName": "user2 lastname",
    "email": "email1@singer.com",
    "password": "12345"
}



# login
### 
post {{BASE_URL}}/auth/login
Content-Type: {{json}}

{
    "email": "email1@singer.com",
    "password": "12345"
}


# get all categories list
###
get {{BASE_URL}}/categories/
Authorization: {{TOKEN}}


# create a category
###
post {{BASE_URL}}/categories/
Authorization: {{TOKEN}}
Content-Type: {{json}}

{
    "name": "fashion"
}


# add product in products collection
###
post {{BASE_URL}}/products/
Authorization: {{TOKEN}}
Content-Type: {{json}}

 {
    "name": "Product 2",
    "description": "Description for Product 2",
    "price": 19.99,
    "category": "fashion",
    "stockQuanity": 100,
    "imageUrl": ["image1.jpg", "image2.jpg"],
    "averageRating": 4.8
  }



# find All Products in a cart by userId
# /userid
###
get {{BASE_URL}}/user/cart/64df2243c3746f359a76d96f
Authorization: {{TOKEN}}


# Add Product To Cart By UserId
###
POST {{BASE_URL}}/user/cart/64df2243c3746f359a76d96f/addProduct
Authorization: {{TOKEN}}
Content-Type: {{json}}

{
    "productId":"64df2269c3746f359a76d978",
    "quantity": 10
}

#  update cart "inc" for increment "dec" for decrement
# /:userid/:flag
###
post {{BASE_URL}}/user/cart/64df2243c3746f359a76d96f/inc
Authorization: {{TOKEN}}
Content-Type: {{json}}

{
    "productId":"64df2269c3746f359a76d978",
    "quantity": 15
}

#! remove product from cart
#* userId/productId
###
DELETE {{BASE_URL}}/user/cart/64df2243c3746f359a76d96f/64df2269c3746f359a76d978
Authorization: {{TOKEN}}


#! place order
# :userid/:productid

###
post {{BASE_URL}}/user/order/64df2243c3746f359a76d96f/placeOrder/64df2269c3746f359a76d978
Authorization: {{TOKEN}}
Content-Type: {{json}}

{
    "shippingAddress": {
      "street": "123 Main Street",
      "city": "Cityville",
      "state": "Stateland",
      "pinCode": "12345",
      "country": "Countryland"
    },
    "paymentMethod": "Credit Card"
}


# OrderHistory by userId
### 
get {{BASE_URL}}/user/orderhistory/64df2243c3746f359a76d96f
Authorization: {{TOKEN}}


# order by id
###
get {{BASE_URL}}/user/order/64df2a029fce2150a130a3b4
Authorization: {{TOKEN}}

# get all categories
###
get {{BASE_URL}}/categories
Authorization: {{TOKEN}}


#get products based on categoryID
###
get {{BASE_URL}}/products/category/64df2260c3746f359a76d975
Authorization: {{TOKEN}}

#get product by productid
###
get {{BASE_URL}}/products/64df2269c3746f359a76d978
Authorization: {{TOKEN}}