@BASE_URL=http://localhost:5000/api
@TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGU4OWY2NDEzZTgwMWM4ZjczZjI4MiIsImlhdCI6MTY5MjMwNjAwMn0.XACxIGgh2eSNquLJJNnVEcsrC11Dd8G3Ax-ZXK67VCI
@json=application/json


# ! register user
###
POST {{BASE_URL}}/auth/register
Content-Type: {{json}}

{
    "firstName": "Sanjeev",
    "lastName": "Choubey",
    "email": "sanjeev@singer.com",
    "password": "12345"
}



# !
### 
post {{BASE_URL}}/auth/login
Content-Type: {{json}}

{
    "email": "sanjeev@email.com",
    "password": "12345"
}


#! get all categories
###
get {{BASE_URL}}/categories/
Authorization: {{TOKEN}}


#! add catgory
###
post {{BASE_URL}}/categories/
Authorization: {{TOKEN}}
Content-Type: {{json}}

{
    "name": "travel"
}


#! add product
###
post {{BASE_URL}}/products/
Authorization: {{TOKEN}}
Content-Type: {{json}}

 {
    "name": "Product 3",
    "description": "Description for Product 3",
    "price": 19.99,
    "category": "fashion",
    "stockQuanity": 100,
    "imageUrl": ["image1.jpg", "image2.jpg"],
    "averageRating": 4.8
  }



# ! all product in cart by userId
# /userid
###
get {{BASE_URL}}/user/cart/64de90ae854dc37c0493e742
Authorization: {{TOKEN}}


# * update cart "inc" for increment "dec" for decrement
/:userid/:flag
###
post {{BASE_URL}}/user/cart/64de90ae854dc37c0493e742/dec
Authorization: {{TOKEN}}
Content-Type: {{json}}

{
    "productId":"64de859f07ca9b890d455ee2",
    "quantity": 1
}

#! remove product from cart
#* userId/productId
###
DELETE {{BASE_URL}}/user/cart/64de90ae854dc37c0493e742/64de93665738084bb9eae885
Authorization: {{TOKEN}}


#! place order
:userid/:productid

###
post {{BASE_URL}}/user/order/64de90ae854dc37c0493e742/placeOrder/64de859f07ca9b890d455ee2
Authorization: {{TOKEN}}
Content-Type: {{json}}

{
    "shippingAddress": {
      "street": "123 Main Street",
      "city": "Cityville",
      "state": "Stateland",
      "pinCode": "12345",
      "country": "Countryland"
    },
    "paymentMethod": "Credit Card"
}


OrderHistory by userId
### 
get {{BASE_URL}}/user/orderhistory/64de90ae854dc37c0493e742
Authorization: {{TOKEN}}
